### PR TITLE
address issue 567

### LINKED ISSUE #567: Cannot pass arbitrary `rng`  to `make_blobs`
Although not in the doc string, you can pass `rng` to `make_blobs` (in addition to `shuffle`). This was presumable added for consistency of API elsewhere (see below). However, it does not work:

```julia
using MLJBase
using StableRNGs

julia> X, y = make_blobs(3, rng=rng)
ERROR: MethodError: no method matching seed!(::StableRNGs.LehmerRNG)
Closest candidates are:
  seed!(::AbstractRNG, ::Nothing) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Random/src/Random.jl:426
  seed!(::StableRNGs.LehmerRNG, ::Integer) at /Users/anthony/.julia/packages/StableRNGs/uwZ1I/src/StableRNGs.jl:39                   
  seed!() at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Random/src/RNGs.jl:362
  ...
Stacktrace:
 [1] shuffle_rows(X::Matrix{Float64}, Y::Vector{Int64}; rng::StableRNGs.LehmerRNG)
   @ MLJBase ~/Dropbox/Julia7/MLJ/MLJBase/src/utilities.jl:133
 [2] finalize_Xy(X::Matrix{Float64}, y::Vector{Int64}, shuffle::Bool, as_table::Bool, eltype
::Type, rng::StableRNGs.LehmerRNG; clf::Bool)                                              
   @ MLJBase ~/Dropbox/Julia7/MLJ/MLJBase/src/data/datasets_synthetic.jl:24
 [3] finalize_Xy(X::Matrix{Float64}, y::Vector{Int64}, shuffle::Bool, as_table::Bool, eltype
::Type, rng::StableRNGs.LehmerRNG)                                                         
   @ MLJBase ~/Dropbox/Julia7/MLJ/MLJBase/src/data/datasets_synthetic.jl:23
 [4] make_blobs(n::Int64, p::Int64; shuffle::Bool, centers::Int64, cluster_std::Float64, center_box::Pair{Float64, Float64}, as_table::Bool, eltype::Type{Float64}, rng::StableRNGs.LehmerRNG)                                                                       
   @ MLJBase ~/Dropbox/Julia7/MLJ/MLJBase/src/data/datasets_synthetic.jl:152
 [5] top-level scope
   @ REPL[17]:1
```

This is probably an issue with the other synthetic data generators. 

Elsewhere randomness is handled with user being able to specify kwargs `rng` and/or `shuffle` with defaults `nothing` and `false`. The logic is summarized in the `Holdout` doc-string, repeated below:

**edit** To this end one can use the helper [MLJBase.shuffle_and_rng](https://github.com/alan-turing-institute/MLJBase.jl/blob/fb183dc07d1b1c10bfc3aef23f7b61eae53abfc7/src/resampling.jl#L21)

---

Pre-shuffling of `rows` is controlled by `rng` and `shuffle`. If `rng`
is an integer, then the `Holdout` keyword constructor resets it to
`MersenneTwister(rng)`. Otherwise some `AbstractRNG` object is
expected.

If `rng` is left unspecified, `rng` is reset to `Random.GLOBAL_RNG`,
in which case rows are only pre-shuffled if `shuffle=true` is
specified.

cc @olivierlabayle

@giordano Can I interest you in picking this up?

### PR DESCRIPTION
**Pull request by OkonSamuel**
fixes #567 and does a little code cleanup.

---> on the `make_blobs` branch
```julia
julia> using MLJBase

julia> using StableRNGs

julia> rng = StableRNG(123)
StableRNGs.LehmerRNG(state=0x000000000000000000000000000000f7)

julia> X, y = make_blobs(3, rng=rng)
(Tables.MatrixTable{Matrix{Float64}} with 3 rows, 2 columns, and schema:
 :x1  Float64
 :x2  Float64, CategoricalArrays.CategoricalValue{Int64, UInt32}[1, 3, 2])
```

cc @ablaom , cc @giordano, cc @olivierlabayle

### CODE REVIEW

File: test/hyperparam/one_dimensional_range_methods.jl [hunk 1]
```diff
@@ -41,6 +41,14 @@ p4 = range(dummy_model, :K, lower=1, upper=3, scale=x->2x)
 
 [p4, p4]
 
+# Starting from julia v"1.7.0-DEV.1233", the default RNG has changed
+# create a function giving julia version dependent default RNG with seed.
+@static if VERSION >= v"1.7.0-DEV.1230"
+    _default_rng(seed) = (rng = TaskLocalRNG(); Random.seed!(rng, seed))
```
Comment (ablaom) [inline test/hyperparam/one_dimensional_range_methods.jl:47]: This looks interesting. Can you point me to some docs?

**Review by ablaom — APPROVED** [review]
Yes this looks like a good approach. My earlier comments about `shuffle` don't really apply in this case, as I see now.

This is very thorough, thank you!

File: test/hyperparam/one_dimensional_range_methods.jl (hunk 1 above)
Comment (OkonSamuel) [reply test/hyperparam/one_dimensional_range_methods.jl:47]: https://docs.julialang.org/en/v1.7-dev/NEWS/#Language-changes
